"""
EPIC30 - Financial Risk & Quantum Optimization

Baseline factor model for Ethereum returns.

The model estimates how ETH daily returns are associated with
major crypto, equity, safe-haven, currency, and volatility factors.

Model:
    ETH_t = alpha
            + beta_1 * BTC_t
            + beta_2 * SP500_t
            + beta_3 * NASDAQ_t
            + beta_4 * GOLD_t
            + beta_5 * USD_t
            + beta_6 * VIX_t
            + epsilon_t

Outputs:
1. OLS regression summary
2. Factor coefficients
3. Variance Inflation Factors (VIF)
4. Model residuals
"""

from pathlib import Path

import pandas as pd
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

TARGET = "ETH"

FACTORS = [
    "BTC",
    "SP500",
    "NASDAQ",
    "GOLD",
    "USD",
    "VIX",
]


# ---------------------------------------------------------
# Load return matrix
# ---------------------------------------------------------

def load_return_matrix(
    filename: str = "market_returns.csv",
) -> pd.DataFrame:
    """
    Load the return matrix generated by data_loader.py.
    """

    project_root = Path(__file__).resolve().parent.parent
    data_path = project_root / "data" / filename

    if not data_path.exists():
        raise FileNotFoundError(
            f"Return matrix not found: {data_path}\n"
            "Run src/data_loader.py first."
        )

    returns = pd.read_csv(
        data_path,
        index_col=0,
        parse_dates=True,
    )

    required_columns = [TARGET] + FACTORS

    missing = [
        column
        for column in required_columns
        if column not in returns.columns
    ]

    if missing:
        raise ValueError(
            f"Missing required columns: {missing}"
        )

    return returns[required_columns].dropna()


# ---------------------------------------------------------
# OLS factor model
# ---------------------------------------------------------

def fit_factor_model(returns: pd.DataFrame):
    """
    Estimate a multiple linear regression for ETH returns.

    ETH is the dependent variable.
    All other configured market factors are explanatory variables.
    """

    y = returns[TARGET]

    X = returns[FACTORS].copy()

    # Add the intercept alpha.
    X = sm.add_constant(X)

    model = sm.OLS(y, X).fit()

    return model


# ---------------------------------------------------------
# Variance Inflation Factor
# ---------------------------------------------------------

def calculate_vif(returns: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate Variance Inflation Factors for explanatory variables.

    VIF helps identify multicollinearity between factors.
    For example, SP500 and NASDAQ may contain overlapping
    information about equity-market risk.
    """

    X = returns[FACTORS].copy()

    vif = pd.DataFrame(
        {
            "factor": X.columns,
            "VIF": [
                variance_inflation_factor(X.values, i)
                for i in range(X.shape[1])
            ],
        }
    )

    return vif.sort_values(
        "VIF",
        ascending=False,
    ).reset_index(drop=True)


# ---------------------------------------------------------
# Factor coefficient table
# ---------------------------------------------------------

def build_coefficient_table(model) -> pd.DataFrame:
    """
    Build a compact coefficient table from the fitted OLS model.
    """

    table = pd.DataFrame(
        {
            "coefficient": model.params,
            "std_error": model.bse,
            "t_stat": model.tvalues,
            "p_value": model.pvalues,
        }
    )

    return table


# ---------------------------------------------------------
# Residual analysis
# ---------------------------------------------------------

def build_residual_data(
    returns: pd.DataFrame,
    model,
) -> pd.DataFrame:
    """
    Store observed ETH returns, model predictions, and residuals.

    The residual represents the component of ETH return that is
    not explained by the selected market factors.
    """

    residuals = pd.DataFrame(
        index=returns.index
    )

    residuals["ETH_return"] = returns[TARGET]
    residuals["predicted_return"] = model.fittedvalues
    residuals["residual"] = model.resid

    return residuals


# ---------------------------------------------------------
# Save outputs
# ---------------------------------------------------------

def save_outputs(
    coefficients: pd.DataFrame,
    vif: pd.DataFrame,
    residuals: pd.DataFrame,
) -> None:
    """
    Save factor-model outputs to the data directory.
    """

    project_root = Path(__file__).resolve().parent.parent
    output_dir = project_root / "data" / "factor_model"

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    coefficients.to_csv(
        output_dir / "coefficients.csv"
    )

    vif.to_csv(
        output_dir / "vif.csv",
        index=False,
    )

    residuals.to_csv(
        output_dir / "residuals.csv"
    )


# ---------------------------------------------------------
# Run directly
# ---------------------------------------------------------

if __name__ == "__main__":

    returns = load_return_matrix()

    print("\nEPIC30 ETH Factor Model")
    print("-----------------------")

    print(f"\nObservations: {len(returns)}")

    model = fit_factor_model(returns)

    print("\nOLS Regression Results")
    print("----------------------")
    print(model.summary())

    coefficients = build_coefficient_table(model)

    print("\nFactor Coefficients")
    print("-------------------")
    print(coefficients)

    vif = calculate_vif(returns)

    print("\nVariance Inflation Factors")
    print("--------------------------")
    print(vif)

    residuals = build_residual_data(
        returns,
        model,
    )

    print("\nModel Diagnostics")
    print("-----------------")
    print(f"R-squared:          {model.rsquared:.4f}")
    print(f"Adjusted R-squared: {model.rsquared_adj:.4f}")
    print(f"Residual std:       {model.resid.std():.6f}")

    save_outputs(
        coefficients,
        vif,
        residuals,
    )

    print(
        "\nOutputs saved to:"
        "\ndata/factor_model/"
    )