"""
EPIC30 - Financial Risk & Quantum Optimization

Visualization of rolling Ethereum factor exposures.

This script reads the rolling factor model results generated by
rolling_factor_model.py and creates time-series plots for:

1. BTC rolling beta
2. NASDAQ rolling beta
3. USD rolling beta
4. VIX rolling beta
5. Rolling R-squared

Primary specification:
    Model B:
        ETH ~ BTC + NASDAQ + GOLD + USD + VIX
"""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

MODEL_FILE = "model_b_nasdaq_window_252.csv"

PLOT_COLUMNS = {
    "coef_BTC": "BTC Rolling Beta",
    "coef_NASDAQ": "NASDAQ Rolling Beta",
    "coef_USD": "USD Rolling Beta",
    "coef_VIX": "VIX Rolling Beta",
    "r_squared": "Rolling R-squared",
}


# ---------------------------------------------------------
# Paths
# ---------------------------------------------------------

def get_project_root() -> Path:
    """
    Return the root directory of the EPIC30 repository.
    """

    return Path(__file__).resolve().parent.parent


# ---------------------------------------------------------
# Load rolling results
# ---------------------------------------------------------

def load_rolling_results(
    filename: str = MODEL_FILE,
) -> pd.DataFrame:
    """
    Load rolling factor model results.
    """

    project_root = get_project_root()

    data_path = (
        project_root
        / "data"
        / "rolling_factor_model"
        / filename
    )

    if not data_path.exists():
        raise FileNotFoundError(
            f"Rolling result file not found: {data_path}\n"
            "Run src/rolling_factor_model.py first."
        )

    results = pd.read_csv(
        data_path,
        index_col="date",
        parse_dates=True,
    )

    results = results.sort_index()

    return results


# ---------------------------------------------------------
# Plot one rolling series
# ---------------------------------------------------------

def plot_series(
    data: pd.DataFrame,
    column: str,
    title: str,
    output_path: Path,
) -> None:
    """
    Plot one rolling factor series and save it as a PNG file.
    """

    if column not in data.columns:
        raise ValueError(
            f"Column '{column}' not found in rolling results."
        )

    fig, ax = plt.subplots(
        figsize=(11, 5)
    )

    ax.plot(
        data.index,
        data[column],
        linewidth=1.5,
    )

    if column.startswith("coef_"):
        ax.axhline(
            0,
            linestyle="--",
            linewidth=1,
        )

    ax.set_title(title)
    ax.set_xlabel("Date")

    if column == "r_squared":
        ax.set_ylabel("R-squared")
    else:
        ax.set_ylabel("Coefficient")

    ax.grid(
        alpha=0.3
    )

    fig.tight_layout()

    fig.savefig(
        output_path,
        dpi=150,
        bbox_inches="tight",
    )

    plt.close(fig)


# ---------------------------------------------------------
# Plot all configured series
# ---------------------------------------------------------

def create_all_plots(
    results: pd.DataFrame,
) -> None:
    """
    Create rolling beta and model-quality plots.
    """

    project_root = get_project_root()

    output_dir = (
        project_root
        / "results"
        / "rolling_factor_model"
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    for column, title in PLOT_COLUMNS.items():

        filename = (
            column.lower()
            .replace("coef_", "")
            + "_rolling.png"
        )

        output_path = (
            output_dir
            / filename
        )

        plot_series(
            data=results,
            column=column,
            title=title,
            output_path=output_path,
        )

        print(
            f"Saved: {output_path}"
        )


# ---------------------------------------------------------
# Print simple diagnostics
# ---------------------------------------------------------

def print_diagnostics(
    results: pd.DataFrame,
) -> None:
    """
    Print basic descriptive statistics for rolling exposures.
    """

    print(
        "\nEPIC30 Rolling Factor Diagnostics"
    )
    print(
        "---------------------------------"
    )

    for column in PLOT_COLUMNS:

        series = results[column]

        print(f"\n{column}")
        print(
            f"Mean:   {series.mean():.4f}"
        )
        print(
            f"Min:    {series.min():.4f}"
        )
        print(
            f"Max:    {series.max():.4f}"
        )
        print(
            f"Latest: {series.iloc[-1]:.4f}"
        )


# ---------------------------------------------------------
# Run directly
# ---------------------------------------------------------

if __name__ == "__main__":

    results = load_rolling_results()

    print_diagnostics(
        results
    )

    create_all_plots(
        results
    )

    print(
        "\nAll plots saved to:"
        "\nresults/rolling_factor_model/"
    )