"""
EPIC30 - Financial Risk & Quantum Optimization

Rolling factor analysis for Ethereum returns.

This script estimates time-varying factor exposures using rolling
regression windows.

Primary specification:
    Model B:
        ETH ~ BTC + NASDAQ + GOLD + USD + VIX

Robustness specification:
    Model A:
        ETH ~ BTC + SP500 + GOLD + USD + VIX

For each rolling window, the script stores:
1. Factor coefficients
2. R-squared
3. Adjusted R-squared
4. HAC / Newey-West p-values
5. Rolling observations

Default window:
    252 trading days ≈ 1 market year
"""

from pathlib import Path

import pandas as pd
import statsmodels.api as sm


TARGET = "ETH"

MODELS = {
    "model_a_sp500": [
        "BTC",
        "SP500",
        "GOLD",
        "USD",
        "VIX",
    ],
    "model_b_nasdaq": [
        "BTC",
        "NASDAQ",
        "GOLD",
        "USD",
        "VIX",
    ],
}


# ---------------------------------------------------------
# Load return matrix
# ---------------------------------------------------------

def load_return_matrix(
    filename: str = "market_returns.csv",
) -> pd.DataFrame:
    """
    Load the return matrix generated by data_loader.py.
    """

    project_root = Path(__file__).resolve().parent.parent
    data_path = project_root / "data" / filename

    if not data_path.exists():
        raise FileNotFoundError(
            f"Return matrix not found: {data_path}\n"
            "Run src/data_loader.py first."
        )

    returns = pd.read_csv(
        data_path,
        index_col=0,
        parse_dates=True,
    )

    return returns.sort_index()


# ---------------------------------------------------------
# Fit one rolling window
# ---------------------------------------------------------

def fit_window(
    window_data: pd.DataFrame,
    factors: list[str],
    hac_lags: int = 5,
) -> dict:
    """
    Fit OLS and HAC inference for one rolling window.
    """

    data = window_data[[TARGET] + factors].dropna()

    y = data[TARGET]

    X = data[factors].copy()
    X = sm.add_constant(X)

    ols_model = sm.OLS(y, X).fit()

    hac_model = sm.OLS(y, X).fit(
        cov_type="HAC",
        cov_kwds={"maxlags": hac_lags},
    )

    result = {
        "n_observations": int(ols_model.nobs),
        "r_squared": ols_model.rsquared,
        "adjusted_r_squared": ols_model.rsquared_adj,
    }

    for parameter in ols_model.params.index:

        result[f"coef_{parameter}"] = ols_model.params[parameter]

        result[f"ols_p_{parameter}"] = ols_model.pvalues[parameter]

        result[f"hac_p_{parameter}"] = hac_model.pvalues[parameter]

    return result


# ---------------------------------------------------------
# Rolling regression
# ---------------------------------------------------------

def run_rolling_model(
    returns: pd.DataFrame,
    factors: list[str],
    window: int = 252,
    hac_lags: int = 5,
) -> pd.DataFrame:
    """
    Run rolling factor regressions over the full dataset.

    Each row represents one rolling window ending on a specific date.
    """

    required_columns = [TARGET] + factors

    data = (
        returns[required_columns]
        .dropna()
        .copy()
    )

    if len(data) < window:
        raise ValueError(
            f"Not enough observations for window={window}. "
            f"Available observations: {len(data)}"
        )

    results = []

    for end_index in range(window, len(data) + 1):

        window_data = data.iloc[
            end_index - window:end_index
        ]

        end_date = window_data.index[-1]

        result = fit_window(
            window_data=window_data,
            factors=factors,
            hac_lags=hac_lags,
        )

        result["date"] = end_date

        results.append(result)

    rolling_results = pd.DataFrame(results)

    rolling_results = (
        rolling_results
        .set_index("date")
        .sort_index()
    )

    return rolling_results


# ---------------------------------------------------------
# Compare rolling model quality
# ---------------------------------------------------------

def build_model_summary(
    rolling_results: dict[str, pd.DataFrame],
) -> pd.DataFrame:
    """
    Build a compact summary across rolling specifications.
    """

    rows = []

    for model_name, results in rolling_results.items():

        rows.append(
            {
                "model": model_name,
                "n_windows": len(results),
                "mean_r_squared": results["r_squared"].mean(),
                "median_r_squared": results["r_squared"].median(),
                "min_r_squared": results["r_squared"].min(),
                "max_r_squared": results["r_squared"].max(),
                "mean_adjusted_r_squared":
                    results["adjusted_r_squared"].mean(),
            }
        )

    return pd.DataFrame(rows)


# ---------------------------------------------------------
# Save outputs
# ---------------------------------------------------------

def save_results(
    rolling_results: dict[str, pd.DataFrame],
    summary: pd.DataFrame,
    window: int,
) -> None:
    """
    Save rolling regression outputs.
    """

    project_root = Path(__file__).resolve().parent.parent

    output_dir = (
        project_root
        / "data"
        / "rolling_factor_model"
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    for model_name, results in rolling_results.items():

        results.to_csv(
            output_dir
            / f"{model_name}_window_{window}.csv"
        )

    summary.to_csv(
        output_dir
        / f"rolling_model_summary_window_{window}.csv",
        index=False,
    )


# ---------------------------------------------------------
# Run directly
# ---------------------------------------------------------

if __name__ == "__main__":

    WINDOW = 252
    HAC_LAGS = 5

    returns = load_return_matrix()

    rolling_results = {}

    print("\nEPIC30 Rolling ETH Factor Models")
    print("--------------------------------")

    for model_name, factors in MODELS.items():

        print(f"\nRunning: {model_name}")

        results = run_rolling_model(
            returns=returns,
            factors=factors,
            window=WINDOW,
            hac_lags=HAC_LAGS,
        )

        rolling_results[model_name] = results

        print(f"Windows: {len(results)}")

        print(
            f"Mean R-squared: "
            f"{results['r_squared'].mean():.4f}"
        )

        print(
            f"Latest R-squared: "
            f"{results['r_squared'].iloc[-1]:.4f}"
        )

        print("\nLatest coefficients:")

        coefficient_columns = [
            column
            for column in results.columns
            if column.startswith("coef_")
        ]

        print(
            results[
                coefficient_columns
            ]
            .iloc[-1]
            .to_string()
        )

    summary = build_model_summary(
        rolling_results
    )

    print("\nRolling Model Summary")
    print("---------------------")

    print(
        summary.to_string(
            index=False,
            float_format=lambda x: f"{x:.4f}",
        )
    )

    save_results(
        rolling_results=rolling_results,
        summary=summary,
        window=WINDOW,
    )

    print(
        "\nResults saved to:"
        "\ndata/rolling_factor_model/"
    )