"""
EPIC30 - Financial Risk & Quantum Optimization

Rolling covariance and correlation analysis.

This module estimates time-varying dependence structures across
the financial market universe.

The outputs provide the statistical foundation for later:

1. Financial network construction
2. Asset clustering / community detection
3. Spectral analysis
4. Systemic-risk modeling
5. Portfolio optimization

Default window:
    252 trading days ≈ 1 market year
"""

from pathlib import Path

import numpy as np
import pandas as pd


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

WINDOW = 252

ASSETS = [
    "ETH",
    "BTC",
    "NASDAQ",
    "SP500",
    "GOLD",
    "USD",
    "VIX",
]


# ---------------------------------------------------------
# Project paths
# ---------------------------------------------------------

def get_project_root() -> Path:
    """
    Return the root directory of the EPIC30 repository.
    """

    return Path(__file__).resolve().parent.parent


# ---------------------------------------------------------
# Load market return matrix
# ---------------------------------------------------------

def load_return_matrix(
    filename: str = "market_returns.csv",
) -> pd.DataFrame:
    """
    Load the return matrix generated by data_loader.py.
    """

    project_root = get_project_root()

    data_path = (
        project_root
        / "data"
        / filename
    )

    if not data_path.exists():
        raise FileNotFoundError(
            f"Return matrix not found: {data_path}\n"
            "Run src/data_loader.py first."
        )

    returns = pd.read_csv(
        data_path,
        index_col=0,
        parse_dates=True,
    )

    missing_assets = [
        asset
        for asset in ASSETS
        if asset not in returns.columns
    ]

    if missing_assets:
        raise ValueError(
            f"Missing required assets: {missing_assets}"
        )

    return (
        returns[ASSETS]
        .dropna()
        .sort_index()
    )


# ---------------------------------------------------------
# Rolling covariance matrices
# ---------------------------------------------------------

def calculate_rolling_covariance(
    returns: pd.DataFrame,
    window: int = WINDOW,
) -> dict[pd.Timestamp, pd.DataFrame]:
    """
    Calculate one covariance matrix for every rolling window.

    Returns
    -------
    dict
        Key:
            End date of the rolling window.

        Value:
            Covariance matrix for that window.
    """

    if len(returns) < window:
        raise ValueError(
            f"Not enough observations for window={window}. "
            f"Available observations: {len(returns)}"
        )

    matrices = {}

    for end_index in range(
        window,
        len(returns) + 1,
    ):

        window_data = returns.iloc[
            end_index - window:end_index
        ]

        end_date = window_data.index[-1]

        covariance_matrix = (
            window_data.cov()
        )

        matrices[end_date] = (
            covariance_matrix
        )

    return matrices


# ---------------------------------------------------------
# Rolling correlation matrices
# ---------------------------------------------------------

def calculate_rolling_correlation(
    returns: pd.DataFrame,
    window: int = WINDOW,
) -> dict[pd.Timestamp, pd.DataFrame]:
    """
    Calculate one correlation matrix for every rolling window.
    """

    if len(returns) < window:
        raise ValueError(
            f"Not enough observations for window={window}. "
            f"Available observations: {len(returns)}"
        )

    matrices = {}

    for end_index in range(
        window,
        len(returns) + 1,
    ):

        window_data = returns.iloc[
            end_index - window:end_index
        ]

        end_date = window_data.index[-1]

        correlation_matrix = (
            window_data.corr()
        )

        matrices[end_date] = (
            correlation_matrix
        )

    return matrices


# ---------------------------------------------------------
# Extract ETH relationships
# ---------------------------------------------------------

def extract_eth_correlations(
    rolling_correlations:
        dict[pd.Timestamp, pd.DataFrame],
) -> pd.DataFrame:
    """
    Extract ETH correlation with every other asset
    from each rolling correlation matrix.

    This creates a time series that shows how ETH's
    relationship with the rest of the market changes.
    """

    rows = []

    for date, matrix in rolling_correlations.items():

        row = {
            "date": date,
        }

        for asset in ASSETS:

            if asset == "ETH":
                continue

            row[f"corr_ETH_{asset}"] = (
                matrix.loc["ETH", asset]
            )

        rows.append(row)

    result = pd.DataFrame(rows)

    return (
        result
        .set_index("date")
        .sort_index()
    )


# ---------------------------------------------------------
# Average absolute correlation
# ---------------------------------------------------------

def calculate_average_market_correlation(
    rolling_correlations:
        dict[pd.Timestamp, pd.DataFrame],
) -> pd.DataFrame:
    """
    Calculate the average absolute pairwise correlation
    across all assets for each rolling window.

    Higher values indicate a market in which assets are
    moving more strongly together.
    """

    rows = []

    for date, matrix in rolling_correlations.items():

        values = matrix.values

        upper_triangle = (
            values[
                np.triu_indices_from(
                    values,
                    k=1,
                )
            ]
        )

        rows.append(
            {
                "date": date,
                "mean_correlation":
                    upper_triangle.mean(),
                "mean_absolute_correlation":
                    np.abs(
                        upper_triangle
                    ).mean(),
            }
        )

    result = pd.DataFrame(rows)

    return (
        result
        .set_index("date")
        .sort_index()
    )


# ---------------------------------------------------------
# Save latest matrices
# ---------------------------------------------------------

def save_latest_matrices(
    rolling_covariances:
        dict[pd.Timestamp, pd.DataFrame],
    rolling_correlations:
        dict[pd.Timestamp, pd.DataFrame],
    window: int,
) -> None:
    """
    Save the latest covariance and correlation matrices.

    Full rolling matrices are not individually written to disk
    because that would create a large number of small files.
    """

    project_root = get_project_root()

    output_dir = (
        project_root
        / "data"
        / "rolling_dependence"
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    latest_date = max(
        rolling_correlations.keys()
    )

    latest_covariance = (
        rolling_covariances[
            latest_date
        ]
    )

    latest_correlation = (
        rolling_correlations[
            latest_date
        ]
    )

    latest_covariance.to_csv(
        output_dir
        / f"latest_covariance_window_{window}.csv"
    )

    latest_correlation.to_csv(
        output_dir
        / f"latest_correlation_window_{window}.csv"
    )


# ---------------------------------------------------------
# Save rolling summaries
# ---------------------------------------------------------

def save_rolling_summaries(
    eth_correlations: pd.DataFrame,
    market_correlation: pd.DataFrame,
    window: int,
) -> None:
    """
    Save compact rolling dependence summaries.
    """

    project_root = get_project_root()

    output_dir = (
        project_root
        / "data"
        / "rolling_dependence"
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    eth_correlations.to_csv(
        output_dir
        / f"eth_correlations_window_{window}.csv"
    )

    market_correlation.to_csv(
        output_dir
        / f"market_correlation_window_{window}.csv"
    )


# ---------------------------------------------------------
# Run directly
# ---------------------------------------------------------

if __name__ == "__main__":

    returns = load_return_matrix()

    print(
        "\nEPIC30 Rolling Covariance "
        "and Correlation Analysis"
    )
    print(
        "------------------------------------------"
    )

    print(
        f"\nObservations: {len(returns)}"
    )

    print(
        f"Assets: {len(ASSETS)}"
    )

    print(
        f"Rolling window: {WINDOW}"
    )

    rolling_covariances = (
        calculate_rolling_covariance(
            returns=returns,
            window=WINDOW,
        )
    )

    rolling_correlations = (
        calculate_rolling_correlation(
            returns=returns,
            window=WINDOW,
        )
    )

    print(
        f"Rolling windows: "
        f"{len(rolling_correlations)}"
    )

    eth_correlations = (
        extract_eth_correlations(
            rolling_correlations
        )
    )

    market_correlation = (
        calculate_average_market_correlation(
            rolling_correlations
        )
    )

    latest_date = (
        max(
            rolling_correlations.keys()
        )
    )

    latest_correlation = (
        rolling_correlations[
            latest_date
        ]
    )

    latest_covariance = (
        rolling_covariances[
            latest_date
        ]
    )

    print(
        f"\nLatest window end: "
        f"{latest_date.date()}"
    )

    print(
        "\nLatest Correlation Matrix"
    )
    print(
        "-------------------------"
    )

    print(
        latest_correlation.round(4)
    )

    print(
        "\nLatest ETH Correlations"
    )
    print(
        "-----------------------"
    )

    latest_eth = (
        latest_correlation["ETH"]
        .drop("ETH")
        .sort_values(
            ascending=False
        )
    )

    print(
        latest_eth.round(4)
    )

    print(
        "\nLatest Covariance Matrix"
    )
    print(
        "------------------------"
    )

    print(
        latest_covariance.round(6)
    )

    print(
        "\nLatest Market Dependence"
    )
    print(
        "------------------------"
    )

    print(
        market_correlation
        .iloc[-1]
        .round(4)
    )

    save_latest_matrices(
        rolling_covariances,
        rolling_correlations,
        WINDOW,
    )

    save_rolling_summaries(
        eth_correlations,
        market_correlation,
        WINDOW,
    )

    print(
        "\nResults saved to:"
        "\ndata/rolling_dependence/"
    )